set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(ENO_ORGANIZATION "Foxxy Soft")
set(ENO_VERSION "1.0.5")
string(TIMESTAMP ENO_YEAR %Y)
set(ENO_COPYRIGHT "Copyright (C) 2011-${ENO_YEAR} ${ENO_ORGANIZATION}")

set(CENO_ORGANIZATION "FoxxySoft")
set(CENO_ENO "Eno")