set_target_properties(all_qmltyperegistrations PROPERTIES FOLDER "Autogen")

#set_target_properties(${CENO_CREATOR}_autogen PROPERTIES FOLDER "Autogen")
set_target_properties(${CENO_CREATOR}_automoc_json_extraction PROPERTIES FOLDER "Autogen")
#set_target_properties(${CENO_CREATOR}_qmlimportscan PROPERTIES FOLDER "Autogen")
set_target_properties(${CENO_CREATOR}_qmltyperegistration PROPERTIES FOLDER "Autogen")
set_target_properties(${CENO_CREATOR}_tooling PROPERTIES FOLDER "Autogen")

#set_target_properties(${CENO_ENGINE}_autogen PROPERTIES FOLDER "Autogen")
set_target_properties(${CENO_ENGINE}_automoc_json_extraction PROPERTIES FOLDER "Autogen")
#set_target_properties(${CENO_ENGINE}_qmlcache PROPERTIES FOLDER "Autogen")
#set_target_properties(${CENO_ENGINE}_qmlcache_autogen PROPERTIES FOLDER "Autogen")
#set_target_properties(${CENO_ENGINE}_qmlimportscan PROPERTIES FOLDER "Autogen")
set_target_properties(${CENO_ENGINE}_qmltyperegistration PROPERTIES FOLDER "Autogen")
set_target_properties(${CENO_ENGINE}_resources_1 PROPERTIES FOLDER "Autogen")
set_target_properties(${CENO_ENGINE}_resources_2 PROPERTIES FOLDER "Autogen")
set_target_properties(${CENO_ENGINE}_tooling PROPERTIES FOLDER "Autogen")
set_target_properties(${CENO_ENGINE}plugin PROPERTIES FOLDER "Autogen")
set_target_properties(${CENO_ENGINE}plugin_init PROPERTIES FOLDER "Autogen")
#set_target_properties(${CENO_ENGINE}plugin_init_autogen PROPERTIES FOLDER "Autogen")

#set_target_properties(${CENO_VIEWER}_autogen PROPERTIES FOLDER "Autogen")
set_target_properties(${CENO_VIEWER}_automoc_json_extraction PROPERTIES FOLDER "Autogen")
#set_target_properties(${CENO_VIEWER}_qmlimportscan PROPERTIES FOLDER "Autogen")
set_target_properties(${CENO_VIEWER}_qmltyperegistration PROPERTIES FOLDER "Autogen")
set_target_properties(${CENO_VIEWER}_tooling PROPERTIES FOLDER "Autogen")